FROM ubuntu

RUN apt update
RUN apt install -y wget git openjdk-17-jdk maven

WORKDIR /app

COPY api-gateway-0.0.1-SNAPSHOT.jar /app/api-gateway-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar", "api-gateway-0.0.1-SNAPSHOT.jar"]