FROM ubuntu:latest

RUN apt update
RUN apt install -y openjdk-17-jdk

WORKDIR /app

COPY hello-wolrd-0.0.1-SNAPSHOT.jar hello-wolrd-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar", "hello-wolrd-0.0.1-SNAPSHOT.jar"]

# docker run -it --rm -e PORT=8088 -p 8081:8088 hello-service-port-parameter