FROM ubuntu:latest

RUN apt update
RUN apt install -y openjdk-17-jdk

WORKDIR /app

#Documentation
EXPOSE 8080

COPY hello-wolrd-0.0.1-SNAPSHOT.jar hello-wolrd.jar

ENTRYPOINT ["java","-jar","hello-wolrd.jar"]
CMD ["a","b","c","d"]

#docker run --rm  -it -p 8080:8080  hello-demo:AN